"""
Optional: train a real YOLOv8 defect-detection model to replace the
classical CV fallback with a proper deep-learning backend.

You do NOT need to run this to demo AeroVision — the classical CV
pipeline in src/detector.py works out of the box. Use this script
once you have (or have downloaded) a labeled aircraft-defect image
dataset, if you want higher accuracy / a "real ML model" for judging.

--------------------------------------------------------------------
STEP 1 — Get a dataset
--------------------------------------------------------------------
This repo does not ship a real defect dataset (only synthetic demo
images in data/sample_images/, generated by generate_samples.py).

Good public sources to search for (verify license terms yourself):
  - Roboflow Universe — search "aircraft defect", "metal surface
    defect", "corrosion detection", "crack detection"
  - Kaggle — search "metal surface defects", "corrosion dataset",
    "aircraft skin defect"
  - NEU surface defect database (steel) — useful as a stand-in for
    generic metal-surface defect detection if aviation-specific data
    is scarce

Organize your dataset in YOLO format:

    dataset/
      images/
        train/*.jpg
        val/*.jpg
      labels/
        train/*.txt   (class x_center y_center width height, normalized)
        val/*.txt
      data.yaml

Example data.yaml:

    path: dataset
    train: images/train
    val: images/val
    names:
      0: crack
      1: corrosion
      2: dent
      3: rivet_damage

--------------------------------------------------------------------
STEP 2 — Train
--------------------------------------------------------------------
    pip install ultralytics
    python train.py --data dataset/data.yaml --epochs 60

This fine-tunes a YOLOv8-nano model (smallest, edge-friendly variant)
and saves the best weights automatically to runs/detect/train/weights/best.pt.

--------------------------------------------------------------------
STEP 3 — Plug it into AeroVision
--------------------------------------------------------------------
    cp runs/detect/train/weights/best.pt models/best.pt

That's it — src/detector.py auto-detects models/best.pt and switches
from the classical CV backend to real YOLOv8 inference the next time
you run the app. No code changes needed.
"""

import argparse


def main():
    parser = argparse.ArgumentParser(description="Train AeroVision YOLOv8 defect detector")
    parser.add_argument("--data", required=True, help="Path to data.yaml")
    parser.add_argument("--epochs", type=int, default=60)
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--model", default="yolov8n.pt", help="Base model to fine-tune (nano = edge-friendly)")
    parser.add_argument("--batch", type=int, default=16)
    args = parser.parse_args()

    try:
        from ultralytics import YOLO
    except ImportError:
        raise SystemExit(
            "ultralytics is not installed. Run: pip install ultralytics torch"
        )

    model = YOLO(args.model)
    model.train(
        data=args.data,
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        name="aerovision_defect_detector",
    )
    print("\nTraining complete.")
    print("Copy the best weights into the app with:")
    print("  cp runs/detect/aerovision_defect_detector/weights/best.pt models/best.pt")


if __name__ == "__main__":
    main()
