"""
Train a real YOLOv8/YOLO11 defect-detection model to replace the
classical CV fallback with a proper deep-learning backend.

You do NOT need to run this to demo AeroVision — the classical CV
pipeline in src/detector.py works out of the box. Use this script
once you have (or have downloaded) a labeled aircraft-defect image
dataset, if you want higher accuracy / a "real ML model" for judging.

CPU vs GPU: this runs fine on CPU (no GPU/CUDA required), it will
just be considerably slower than on a GPU. If you have access to a
free GPU runtime (e.g. Google Colab), training there and copying the
resulting best.pt back is much faster for the same --epochs. Use
--device to control this explicitly (default: "cpu"; pass "0" for
first CUDA GPU if available).

--------------------------------------------------------------------
STEP 1 — Get a dataset
--------------------------------------------------------------------
This repo does not ship a real defect dataset (only synthetic demo
images in data/sample_images/, generated by generate_samples.py).

Good public sources to search for (verify license terms yourself):
  - Roboflow Universe — search "aircraft defect", "metal surface
    defect", "corrosion detection", "crack detection"
  - Kaggle — search "metal surface defects", "corrosion dataset",
    "aircraft skin defect"
  - NEU surface defect database (steel) — useful as a stand-in for
    generic metal-surface defect detection if aviation-specific data
    is scarce

Organize your dataset in YOLO format. If you download from Roboflow
Universe and export as "YOLOv8", the zip already comes in this
layout — just unzip it as-is into dataset/, no reorganizing needed:

    dataset/
      train/
        images/*.jpg
        labels/*.txt
      valid/
        images/*.jpg
        labels/*.txt
      data.yaml            # Roboflow writes this for you, e.g.:
                            #   train: train/images
                            #   val: valid/images
                            #   names: ['crack', 'dent', 'corrosion']

(scripts/validate_dataset.py and this script both understand this
layout directly — they resolve whatever train:/val: say in data.yaml
and find the matching labels folder automatically, the same way
ultralytics does internally.)

If you're building the dataset by hand instead, the other common
layout also works:

    dataset/
      images/
        train/*.jpg
        val/*.jpg
      labels/
        train/*.txt   (class x_center y_center width height, normalized)
        val/*.txt
      data.yaml

Example data.yaml — class names MUST match these exactly (lowercase,
underscore in rivet_damage) since they flow straight through to
severity.py's TYPE_CRITICALITY and report.py's COLOR_MAP, which key
off these exact strings and silently fall back to defaults on any
mismatch:

    path: /absolute/path/to/dataset   # use an ABSOLUTE path here — see note below
    train: images/train
    val: images/val
    names:
      0: crack
      1: corrosion
      2: dent
      3: rivet_damage

IMPORTANT — use an absolute path for `path:`, not a relative one like
`.`: ultralytics resolves a relative `path` against its own working
directory / global datasets setting, NOT against the folder data.yaml
lives in. A relative path here can silently point ultralytics at the
wrong directory (confirmed during testing: `path: .` failed with
"images not found" even though the dataset was valid).

--------------------------------------------------------------------
STEP 2 — Validate (recommended, done automatically below)
--------------------------------------------------------------------
    python scripts/validate_dataset.py --data dataset/data.yaml

This script calls the same validation automatically before training
and aborts on failure. Pass --skip-validation to bypass it.

--------------------------------------------------------------------
STEP 3 — Train
--------------------------------------------------------------------
    pip install ultralytics
    python train.py --data dataset/data.yaml --epochs 60

This fine-tunes a pretrained YOLOv8-nano/YOLO11-nano checkpoint
(COCO-pretrained weights, downloaded automatically by ultralytics —
NOT trained from scratch) and saves the best weights to:

    runs/detect/aerovision_defect_detector/weights/best.pt

--------------------------------------------------------------------
STEP 4 — Plug it into AeroVision
--------------------------------------------------------------------
    cp runs/detect/aerovision_defect_detector/weights/best.pt models/best.pt

That's it — src/detector.py auto-detects models/best.pt and switches
from the classical CV backend to real YOLO inference the next time
you run the app. No code changes needed there.
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))


def main():
    parser = argparse.ArgumentParser(description="Train AeroVision YOLO defect detector")
    parser.add_argument("--data", required=True, help="Path to data.yaml")
    parser.add_argument("--epochs", type=int, default=60)
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--model", default="yolov8n.pt",
                         help="Base pretrained checkpoint to fine-tune (nano = edge-friendly). "
                              "COCO-pretrained, downloaded automatically by ultralytics.")
    parser.add_argument("--batch", type=int, default=16)
    parser.add_argument("--device", default="cpu",
                         help='Training device: "cpu" (default, no GPU required, slower) '
                              'or e.g. "0" for the first CUDA GPU if available.')
    parser.add_argument("--skip-validation", action="store_true",
                         help="Skip the automatic dataset validation step before training.")
    args = parser.parse_args()

    if not args.skip_validation:
        from scripts.validate_dataset import validate_dataset
        print("Running dataset validation before training (use --skip-validation to bypass)...")
        if not validate_dataset(args.data):
            raise SystemExit(
                "\nDataset validation FAILED — fix the issues above before training, "
                "or re-run with --skip-validation to proceed anyway (not recommended)."
            )
        print("\nDataset validation passed. Proceeding to training.\n")

    try:
        from ultralytics import YOLO
    except ImportError:
        raise SystemExit(
            "ultralytics is not installed. Run: pip install ultralytics torch"
        )

    if args.device == "cpu":
        print("Training on CPU — this will be slow for larger datasets/epoch counts. "
              "For faster training, use a GPU runtime (e.g. Google Colab) and pass "
              '--device 0, then copy the resulting best.pt back into this project.\n')

    model = YOLO(args.model)  # fine-tunes from COCO-pretrained weights, not from scratch
    results = model.train(
        data=args.data,
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        device=args.device,
        name="aerovision_defect_detector",
    )

    print("\nTraining complete.")

    # Print final validation metrics (ultralytics logs these throughout training;
    # this surfaces a clean one-line summary at the end).
    metrics = getattr(results, "results_dict", None) or getattr(results, "box", None)
    try:
        val_metrics = model.val()
        print(f"\nFinal validation metrics:")
        print(f"  mAP50:     {val_metrics.box.map50:.4f}")
        print(f"  mAP50-95:  {val_metrics.box.map:.4f}")
        print(f"  Precision: {val_metrics.box.mp:.4f}")
        print(f"  Recall:    {val_metrics.box.mr:.4f}")
    except Exception as e:
        print(f"  (Could not print summary metrics automatically: {e}. "
              f"Check runs/detect/aerovision_defect_detector/ for full logs/plots.)")

    print("\nCopy the best weights into the app with:")
    print("  cp runs/detect/aerovision_defect_detector/weights/best.pt models/best.pt")


if __name__ == "__main__":
    main()
